Adicionando parametro de população aos algoritmos
GuilhermeAGouveia/heuristic-scientific-research pull request #41
Opened 2023-08-03 16:15 UTC by ViniciusBastoss

Foi adicionado a cada algoritmo o parâmetro population que permite a cada algoritmo receber uma população inicial e caso population == NULL uma população aleatória é gerada.

2023-08-03 23:05 UTC, GuilhermeAGouveia requested changes

2023-08-03 23:05 UTC, GuilhermeAGouveia commented on src/algorithms/pso.c
> +    }
tenta usar o generate_island aqui tbm

2023-08-03 23:05 UTC, GuilhermeAGouveia commented on src/main.c
> +    population->individuos = generate_population(124, 10, domainAux, 3);
generate_island

2023-08-03 23:09 UTC, GuilhermeAGouveia commented
Quando executei o seguinte comando `./evol -A a` deu erro:

![image](https://github.com/GuilhermeAGouveia/heuristic-scientific-research/assets/81968354/0af2e574-aa11-4b2f-acfd-77aefdeabbe6)

2023-08-03 23:10 UTC, GuilhermeAGouveia commented on src/main.c
> +    population->individuos = generate_population(124, 10, domainAux, 3);
Só subtituir por isso:

```suggestion
   population = generate_island(1, 124, 10, domainAux, 3);

```

2023-08-03 23:28 UTC, GuilhermeAGouveia commented
Usa a condicional `if (population == NULL)`, igual vc fez no ACO, porque é bom manter consistência, e desse jeito ficou melho tbm

2023-08-04 14:17 UTC, ViniciusBastoss commented on src/algorithms/clonalg.c
> +    }
Estava assim pois estava acontecendo um bug, mas percebi que a causa era a forma como o teste estava sendo feito

2023-08-04 16:47 UTC, GuilhermeAGouveia approved these changes

2023-08-04 16:48 UTC, GuilhermeAGouveia commented
Brabo

2023-08-04 16:48 UTC, merged