Coleta de dados genética
GuilhermeAGouveia/heuristic-scientific-research pull request #60
Opened 2024-04-09 21:38 UTC by ViniciusBastoss

2024-04-23 01:37 UTC, GuilhermeAGouveia requested changes

2024-04-23 01:37 UTC, GuilhermeAGouveia commented on src/algorithms/aco.c
>      free(pheromones_candidates);
sobre desalocar a matriz apenas utilizando free: https://chat.openai.com/share/dbc40d9b-06ae-4f40-b550-fd4738a091f7

No commom.c tem uma função de desalocar matriz já, só utilizar ela: `destroy_matriz`

2024-04-23 01:37 UTC, GuilhermeAGouveia commented on src/algorithms/aco.c
> +    candidates = (individuo *)malloc(parameters.num_candidates * sizeof(individuo));
pelo que entendi essas variáveis globais não podem ser perdidas durante a troca de épocas, se sim, faz sentido ficar alocando elas aqui toda vez que a função `aco` for chamada pelos algoritmos de ilhas, o comentário vale tbm para: sigma, pheromones_candidates, probability_interval. Se for caso seria melhor alocar **todas (incluindo cada linha)** as posições da matriz globalmente tbm, pra que seja feito apenas uma vez

Agora se pode ser perdido, lembrar de desalocar a memória no fim da função `aco`

2024-04-23 01:39 UTC, GuilhermeAGouveia commented on src/algorithms/aco.c
> +        select_next_position(pheromones, individuos, parameters.dimension, best_individuo);
essa função parece ser muito pesada, revisar com calma as operações e se não dá pra otimizar nada

2024-04-23 19:02 UTC, ViniciusBastoss commented on src/algorithms/aco.c
> +            probability_interval[j][i].max = start + prob;
Não, a ideia aqui é para cada dimensão i calcular a probabilidade para cada indivíduo j naquela dimensão.

2024-04-24 00:13 UTC, ViniciusBastoss commented on src/algorithms/aco.c
> +        select_next_position(pheromones, individuos, parameters.dimension, best_individuo);
O que estava pesando o algoritmo era um erro de divisão por 0 ao calcular os feromônios, pois sigma[i] eventualmente seria 0.

2024-04-24 00:21 UTC, ViniciusBastoss commented on src/algorithms/aco.c
> +        parameters.p_exploitation = 0.00;
A exploração acaba não permitindo que o algoritmo convirja, portanto foi alterada para 0.

2024-06-24 21:16 UTC, caioreius approved these changes

2024-07-16 14:09 UTC, caioreius approved these changes

2024-07-17 10:19 UTC, GuilhermeAGouveia approved these changes

2024-07-17 10:19 UTC, merged